### ISSUE TITLE
Resume training

### ISSUE THREAD

**Issue by Zizzzzzzz** [Peterande/SAST#2]
Thanks for your wonderful job! When I attempted to resume training from a checkpoint, I encountered this issue:
![image](https://github.com/Peterande/SAST/assets/88081108/c1ef6d7d-d263-47d2-9bd0-7b7faa7b80db)

**Comment by Peterande** [comment]
That's for logging sparsity only. 
Try annotating that part directly or reinitializing p_loss as in detention.py:

def smooth_loss(self, step_loss, idx):
        if self.trainer.global_step == 0:
            self.iou_loss, self.conf_loss, self.cls_loss, self.p_loss = 0, 0, 0, 0

**Comment by Zizzzzzzz** [comment]
Thank you! I have another question regarding training resources. When I use the same dataset, the same hardware (two 3090 GPUs), and the same training settings (2 batch_size per GPU), I notice that SAST consumes about four times the gpu memory of RVT and takes six times longer to train for one epoch. What could be the reason for this? Are there significant differences between your training code and that of RVT?

**Comment by Peterande** [comment]
Pls check the other settings in configs.
Are you making sure that the model_size (RVT-B,S,T), and dataset(Gen1/Gen4) are consistent?

**Comment by Peterande** [comment]
I checked my records of training RVT and SAST at the time and there was no significant difference in training duration

**Comment by Peterande** [comment]
One difference is that the total number of steps set has been increased from 400K to 600K, but it is probably around 40K+ to achieve the performance in the paper

**Comment by Zizzzzzzz** [comment]
> Pls check the other settings in configs. Are you making sure that the model_size (RVT-B,S,T), and dataset(Gen1/Gen4) are consistent?

The model size is the same. I just tested on the GEN1 dataset, and indeed, the training resource consumption of SAST and RVT does not show significant differences. However, when I use my own dataset (which has sparser events), the differences mentioned above occur.

**Comment by Peterande** [comment]
Such a big difference is unlikely to be caused by model hyperparameters. It would be best to carefully check other global settings in debug mode, and you can also use profiling tools to examine where the GPU memory is being used.

**Comment by Zizzzzzzz** [comment]
Thanks, everything worked fine after I used the code I re-downloaded from github, I probably changed something by accident!
