### ISSUE TITLE
checkpoints

### ISSUE THREAD

**Issue by silvada95** [Peterande/SAST#6]
Hi,

I am trying to download the pre-trained checkpoints. However, I get redirected to the main page whenever I click on the link.

**Comment by Peterande** [comment]
I apologize for the inconvenience, but the pre-trained checkpoint file has been removed from the educational network's OneDrive. Currently, I am occupied with another important open-source project and temporarily cannot access the original host. I am very sorry for the trouble this may cause. You may need to retrain the model yourself for the time being.
