### ISSUE TITLE
epoc

### ISSUE THREAD

**Issue by xjyisok** [Peterande/SAST#8]
Hi
how much  number of iterations (it) in one epoch during training while my epoc0 dosen't stop even reach 3000 it my batch_size is 2

**Comment by Peterande** [comment]
Our training strategies are all based on iterations (it), and since we adopt a hybrid training strategy from RVT, there isn't a clear concept of epochs. You can control the evaluation cycle by changing the validation validation.val_check_interval=10000 in the launch command.

**Comment by xjyisok** [comment]
I see that in code one ckpt file will be saved after one epoch. but after training one epoch in folder output I only see some .yaml file.like this
![image](https://github.com/user-attachments/assets/e3de4bd3-b72a-4041-9c94-3d64f93c71a6)

![image](https://github.com/user-attachments/assets/66ce3c9d-5ca8-4aca-ad2e-c7c06606046a)

**Comment by Peterande** [comment]
https://github.com/Peterande/SAST/blob/b40ab1aa135f61d46dd8e3f4da1381fa733c3c58/train.py#L154

You can modify "default_root_dir" to the path.

_Originally posted by @Peterande in https://github.com/Peterande/SAST/issues/9#issuecomment-2423698060_
            
The ckpt file will be saved in "default_root_dir".
